name: Coveralls
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14.2
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-coveralls-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-coveralls-
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.2
          elixir-version: 1.13.3
      - run: mix deps.get
      - run: MIX_ENV=test mix coveralls.json
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1

