name: Coveralls
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11.6
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-ex_check_tests-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-ex_check_tests-
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.1
          elixir-version: 1.12.3
      - run: mix deps.get
      - run: MIX_ENV=test mix coveralls.json
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-ex_check_tests-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-ex_check_tests-

