name: Credo
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14.2
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-ex_check_tests-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-ex_check_tests-
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.2
          elixir-version: 1.13.3
      - run: mix deps.get
      - run: MIX_ENV=test mix credo --strict
      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-ex_check_tests-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-ex_check_tests-

